routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register'=>false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware'=>['auth']], function()
{
    //users
    Route::resource('users', 'UserController');

    //certification types
    Route::resource('certification_types', 'CertificationTypeController');

    //certifications
    Route::group(['prefix'=>'certifications'], function(){
        Route::get('/expiring_index', 'CertificationController@expiringIndex')->name('certifications.expiring_index');
        Route::get('/download-document/{certification}', 'CertificationController@downloadDocument')->name('certifications.download_document');
    });
    Route::resource('certifications', 'CertificationController');

    //eye tests
    Route::group(['prefix'=>'eye_tests'], function(){
        Route::get('/expiring_index', 'EyeTestController@expiringIndex')->name('eye_tests.expiring_index');
        Route::get('/download-document/{eye_test}', 'EyeTestController@downloadDocument')->name('eye_tests.download_document');
    });
    Route::resource('eye_tests', 'EyeTestController');

    //equipment
    Route::resource('equipment', 'EquipmentController');

    // equipment calibrations
    Route::group(['prefix'=>'equipment_calibrations'], function(){
        Route::get('/download-document/{equipment_calibration}', 'EquipmentCalibrationController@downloadDocument')->name('equipment_calibrations.download_document');
        Route::get('/expiring_index', 'EquipmentCalibrationController@expiringIndex')->name('equipment_calibrations.expiring_index');
    });
    Route::resource('equipment_calibrations', 'EquipmentCalibrationController');

    // equipment users
    Route::group(['prefix'=>'equipment_users'], function(){
        Route::get('/return/{equipment_user}', 'EquipmentUserController@return')->name('equipment_users.return');
    });
    Route::resource('equipment_users', 'EquipmentUserController');
});

app/Certification.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\CertificationType;
use App\User;
use Carbon\Carbon;

class Certification extends Model
{

    // Status database constants
    const STATUS_ACTIVE = 1;
    const STATUS_EXPIRED = 2;

    // Properties
    protected $readStatuses = [
        self::STATUS_ACTIVE => 'Active',
        self::STATUS_EXPIRED => 'Expired',
    ];

    protected $fillable = [
        'certification_type_id', 'user_id', 'certified_by', 'document_path', 'certification_date', 'expiry_date', 'status', 'renewal_for_id', 'recertification_for_id',
    ];

    protected $reminder_period = 3; //months

    // Relationships
    public function certificationType()
    {
        return $this->belongsTo(CertificationType::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function renewal()
    {
        return $this->hasOne(self::class, 'renewal_for_id');
    }

    public function recertification()
    {
        return $this->hasOne(self::class, 'recertification_for_id');
    }

    // Accessors
    public function getTypeAttribute()
    {
        return $this->certificationType->method;
    }

    public function getReadStatusAttribute()
    {
        return $this->readStatuses[$this->status];
    }

    public function getCodeAttribute()
    {
        return $this->certificationType->code_level;
    }

    public function getDocumentStorePathAttribute()
    {
        return '/users/' . $this->user_id . '/certifications';
    }

    // Mutators



    // Scopes
    public function scopeGetRenewalRequired($query)
    {
        $date = Carbon::parse(date('Y-m-d'))->addMonths($this->reminder_period);
        return $query->where('renewal_for_id', null)
                        ->where('expiry_date', '<', $date)
                        ->whereDoesntHave('renewal')
                        ->get();
    }

    public function scopeGetRecertificationRequired($query)
    {
        $date = Carbon::parse(date('Y-m-d'))->addMonths($this->reminder_period);
        return $query->where('renewal_for_id', '!=', null)
                        ->where('expiry_date', '<', $date)
                        ->whereDoesntHave('recertification')
                        ->get();
    }

    public function scopeGetExpires($query)
    {
        $date = Carbon::parse(date('Y-m-d'));
        return $query->where('expiry_date', '<', $date)
                        ->get();
    }

    // Context
    public function requiresRenewal()
    {
        if ($this->renewal_for_id == null)
        {
            return true;
        }
    }

    public function requiresRecertification()
    {
        if ($this->renewal_for_id != null)
        {
            return true;
        }
    }
}

app/EquipmentCalibration.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Equipment;
use Carbon\Carbon;

class EquipmentCalibration extends Model
{
    // Constants
    const STATUS_ACTIVE = 1;
    const STATUS_EXPIRED = 2;

    // Properties
    protected $fillable = [
        'equipment_id', 'calibrated_by', 'document_path', 'calibration_date', 'expiry_date', 'status'
    ];

    protected $readStatuses = [
        self::STATUS_ACTIVE => 'Active',
        self::STATUS_EXPIRED => 'Expired',
    ];

    protected $reminder_period = 3; // Months


    // Relationships
    public function equipment()
    {
        return $this->belongsTo(Equipment::class);
    }

    public function renewal()
    {
        return $this->hasOne(self::class, 'renewal_for_id');
    }

    public function renewalFor()
    {
        return $this->belongsTo(self::class, 'renewal_for_id');
    }

    // Accessors
    public function getReadStatusAttribute()
    {
        return $this->readStatuses[$this->status];
    }

    public function getDocumentStorePathAttribute()
    {
        return '/equipment/' . $this->equipment_id . '/calibration_certificates';
    }

    // Scopes
    public function scopeGetExpires($query)
    {
        $date = Carbon::parse(date('Y-m-d'));
        return $query->where('status', self::STATUS_ACTIVE)
                        ->where('expiry_date', '<' , $date)
                        ->orWhereHas('renewal')
                        ->get();
    }

    public function scopeGetRequiresRenewal($query)
    {
        $date = Carbon::parse(date('Y-m-d'))->addMonths($this->reminder_period);
        return $query->where('expiry_date', '<', $date)
                        ->whereDoesntHave('renewal')
                        ->get();
    }

    // Context
    public function requiresRenewal()
    {
        $date = Carbon::parse(date('Y-m-d'))->addMonths($this->reminder_period);
        if ($this->renewal == null && $this->expiry_date < $date)
        {
            return true;
        }
        return false;
    }
}

app/Http/Controllers/EquipmentCalibrationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\EquipmentCalibrationRequest;
use App\EquipmentCalibration;
use App\Equipment;
use App\ModelLogic\EquipmentCalibration\EquipmentCalibrationLogic;
use App\ExternalServices\FileStorage\DocumentHandler;

class EquipmentCalibrationController extends Controller
{
    public function __construct(EquipmentCalibrationLogic $equipmentCalibrationLogic)
    {
        $this->equipmentCalibrationLogic = $equipmentCalibrationLogic;
        $this->middleware('admin');
        $this->authorizeResource(EquipmentCalibration::class);
    }

    public function expiringIndex()
    {
        $equipment_calibrations = EquipmentCalibration::getRequiresRenewal();

        return view('equipment_calibrations.expiring_index', compact('equipment_calibrations'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $equipment = Equipment::findOrFail($request->equipment_id);
        $equipment_calibration = EquipmentCalibration::find($request->equipment_calibration_id); // in the case of renewals

        return view('equipment_calibrations.create', compact('equipment', 'equipment_calibration'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EquipmentCalibrationRequest $request)
    {
        $this->equipmentCalibrationLogic->create($request);

        return redirect(route('equipment.show', $request->equipment_id));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(EquipmentCalibration $equipment_calibration)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(EquipmentCalibration $equipment_calibration)
    {
        return view('equipment_calibrations.edit', compact('equipment_calibration'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(EquipmentCalibrationRequest $request, EquipmentCalibration $equipment_calibration)
    {
        $this->equipmentCalibrationLogic->update($equipment_calibration, $request);

        return redirect(route('equipment.show', $equipment_calibration->equipment_id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(EquipmentCalibration $equipment_calibration)
    {
        $this->equipmentCalibrationLogic->delete($equipment_calibration);

        return redirect(route('equipment.show', $equipment_calibration->equipment_id));
    }

    // Download document
    public function downloadDocument(EquipmentCalibration $equipment_calibration)
    {
        return DocumentHandler::download($equipment_calibration->document_path);
    }
}

resources/views/equipment_calibrations/create.blade.php
@extends('layouts.app')

@section('content')

<h1>Add Calibration For {{$equipment->type}} - {{$equipment->asset_number}}</h1>

{!! Form::open(['method'=>'POST', 'action'=>['EquipmentCalibrationController@store'], 'files'=>true]) !!}

    {!! Form::hidden('equipment_id', $equipment->id) !!}

    @if ($equipment_calibration)

        {!! Form::hidden('equipment_calibration_id', $equipment_calibration->id) !!}

    @endif

    <div class='form-group'>
        {!! Form::label('calibrated_by', 'Calibrated By:') !!}
        {!! Form::text('calibrated_by', null, ['class'=>'form-control']) !!}
        @error('calibrated_by')
            <p class='text-danger'>{{$message}}</p>
        @enderror
    </div>

    <div class='form-group'>
        {!! Form::label('file', 'Add File:') !!}<br>
        {!! Form::file('file') !!}
        @error('file')
            <p class='text-danger'>{{$message}}</p>
        @enderror
    </div>

    <div class='form-group'>
        {!! Form::label('calibration_date', 'Calibration Date:') !!}
        {!! Form::date('calibration_date', null, ['class'=>'form-control']) !!}
        @error('calibration_date')
            <p class='text-danger'>{{$message}}</p>
        @enderror
    </div>

    <div class='form-group'>
        {!! Form::label('expiry_date', 'Expiry Date:') !!}
        {!! Form::date('expiry_date', null, ['class'=>'form-control']) !!}
        @error('expiry_date')
            <p class='text-danger'>{{$message}}</p>
        @enderror
    </div>

    {!! Form::submit('Add Calibration', ['class'=>'btn btn-primary']) !!}

{!! Form::close() !!}

@stop

resources/views/equipment_calibrations/edit.blade.php
@extends('layouts.app')

@section('content')

<h1>Add Calibration For {{$equipment_calibration->equipment->type}} - {{$equipment_calibration->equipment->asset_number}}</h1>

{!! Form::model($equipment_calibration, ['method'=>'PATCH', 'action'=>['EquipmentCalibrationController@update', $equipment_calibration], 'files'=>true]) !!}

    <div class='form-group'>
        {!! Form::label('calibrated_by', 'Calibrated By:') !!}
        {!! Form::text('calibrated_by', null, ['class'=>'form-control']) !!}
        @error('calibrated_by')
            <p class='text-danger'>{{$message}}</p>
        @enderror
    </div>

    <div class='form-group'>
        {!! Form::label('file', 'Add File:') !!}<br>
        {!! Form::file('file') !!}
        @error('file')
            <p class='text-danger'>{{$message}}</p>
        @enderror
    </div>

    <div class='form-group'>
        {!! Form::label('calibration_date', 'Calibration Date:') !!}
        {!! Form::date('calibration_date', null, ['class'=>'form-control']) !!}
        @error('calibration_date')
            <p class='text-danger'>{{$message}}</p>
        @enderror
    </div>

    <div class='form-group'>
        {!! Form::label('expiry_date', 'Expiry Date:') !!}
        {!! Form::date('expiry_date', null, ['class'=>'form-control']) !!}
        @error('expiry_date')
            <p class='text-danger'>{{$message}}</p>
        @enderror
    </div>

    {!! Form::submit('Save Changes', ['class'=>'btn btn-secondary']) !!}

{!! Form::close() !!}

@stop

resources/views/equipment_calibrations/expiring_index.blade.php
@extends('layouts.app')

@section('content')

<h1>Expiring Equipment Calibrations</h1>

<br>

<table class="table tabel-sm table-hover">

    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Asset Number</th>
            <th scope="col">Type</th>
            <th scope="col">Manufacturer</th>
            <th scope="col">Model</th>
            <th scope="col">Serial Number</th>
            <th scope="col">Calibration Status</th>
            <th scope="col">Expiry Date</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>

    <tbody>
        @if (count($equipment_calibrations) > 0)

            @foreach ($equipment_calibrations as $equipment_calibration)
                <tr>
                    <th scope="row">{{$equipment_calibration->id}}</th>
                    <td><a href="{{route('equipment.show', $equipment_calibration->equipment)}}">{{$equipment_calibration->equipment->asset_number}}</a></td>
                    <td>{{$equipment_calibration->equipment->type}}</td>
                    <td>{{$equipment_calibration->equipment->manufacturer}}</td>
                    <td>{{$equipment_calibration->equipment->model}}</td>
                    <td>{{$equipment_calibration->equipment->serial_number}}</td>
                    <td>{{$equipment_calibration->read_status}}</td>
                    <td>{{$equipment_calibration->expiry_date}}</td>
                    <td>
                        <div class="btn-group btn-group-sm" role="group" aria-label="...">

                            @can('update', $equipment_calibration)
                                {!! Form::open(['method'=>'GET', 'action'=>['EquipmentCalibrationController@create'], 'files'=>false]) !!}

                                    {!! Form::hidden('equipment_id', $equipment_calibration->equipment_id) !!}

                                    {!! Form::hidden('equipment_calibration_id', $equipment_calibration->id) !!}

                                    {!! Form::submit('Renew', ['class'=>'btn btn-sm btn-success']) !!}

                                {!! Form::close() !!}
                            @endcan

                        </div>
                    </td>
                </tr>
            @endforeach

        @else
            <tr>
                <th></th>
                <td colspan="5">There are no equipment calibrations that are expiring</td>
            </tr>
        @endif
  </tbody>
</table>

@stop