routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register'=>false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware'=>['auth']], function()
{
    //users
    Route::resource('users', 'UserController');

    //certification types
    Route::resource('certification_types', 'CertificationTypeController');

    //certifications
    Route::group(['prefix'=>'certifications'], function(){
        Route::get('/expiring_index', 'CertificationController@expiringIndex')->name('certifications.expiring_index');
        Route::get('/download-document/{certification}', 'CertificationController@downloadDocument')->name('certifications.download_document');
    });
    Route::resource('certifications', 'CertificationController');

    //eye tests
    Route::group(['prefix'=>'eye_tests'], function(){
        Route::get('/expiring_index', 'EyeTestController@expiringIndex')->name('eye_tests.expiring_index');
        Route::get('/download-document/{eye_test}', 'EyeTestController@downloadDocument')->name('eye_tests.download_document');
    });
    Route::resource('eye_tests', 'EyeTestController');

    //equipment
    Route::resource('equipment', 'EquipmentController');

    // equipment calibrations
    Route::group(['prefix'=>'equipment_calibrations'], function(){
        Route::get('/download-document/{equipment_calibration}', 'EquipmentCalibrationController@downloadDocument')->name('equipment_calibrations.download_document');
        Route::get('/expiring_index', 'EquipmentCalibrationController@expiringIndex')->name('equipment_calibrations.expiring_index');
    });
    Route::resource('equipment_calibrations', 'EquipmentCalibrationController');

    // equipment users
    Route::group(['prefix'=>'equipment_users'], function(){
        Route::get('/return/{equipment_user}', 'EquipmentUserController@return')->name('equipment_users.return');
    });
    Route::resource('equipment_users', 'EquipmentUserController');
});

app/CertificationType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CertificationType extends Model
{

    protected $fillable = [
        'method', 'code', 'description', 'level', 'authority', 'months_valid',
    ];

    protected $appends = [
        'code_level'
    ];

    // Accessors
    public function getReadExpiryAttribute()
    {
        return "This certification needs to be renewed every " . $this->months_valid . " months";
    }

    public function getCodeLevelAttribute()
    {
        return $this->code.'-'.$this->level;
    }
}

app/Http/Controllers/CertificationTypeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\CertificationType;
use App\Http\Requests\CertificationTypeRequest;

class CertificationTypeController extends Controller
{

    public function __construct()
    {
        $this->middleware('admin')->except(['show']);
        $this->authorizeResource(CertificationType::class);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $certification_types = CertificationType::all();

        return view('certification_types.index', compact('certification_types'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CertificationTypeRequest $request)
    {
        CertificationType::create($request->all());

        return redirect(route('certification_types.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(CertificationType $certification_type)
    {
        return view('certification_types.show', compact('certification_type'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(CertificationType $certification_type)
    {
        return view('certification_types.edit', compact('certification_type'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CertificationTypeRequest $request, CertificationType $certification_type)
    {
        $certification_type->update($request->all());

        return redirect(route('certification_types.show', $certification_type));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(CertificationType $certification_type)
    {
        $certification_type->delete();

        return redirect(route('certification_types.index'));
    }
}

resources/views/certification_types/edit.blade.php
@extends('layouts.app')

@section('content')

    <h1>Edit Certification</h1>

    <div class="col-8">
        {!! Form::model($certification_type, ['method'=>'PATCH', 'action'=>['CertificationTypeController@update', $certification_type], 'files'=>false]) !!}

        <div class='form-group'>
            {!! Form::label('method', 'Method:') !!}
            {!! Form::text('method', null, ['class'=>'form-control']) !!}
            @error('method')
                <p class='text-danger'>{{$message}}</p>
            @enderror
        </div>

        <div class='form-group'>
            {!! Form::label('code', 'Short Code:') !!}
            {!! Form::text('code', null, ['class'=>'form-control']) !!}
            @error('code')
                <p class='text-danger'>{{$message}}</p>
            @enderror
        </div>

        <div class='form-group'>
            {!! Form::label('description', 'Description:') !!}
            {!! Form::textarea('description', null, ['class'=>'form-control ', 'rows'=>3]) !!}
            @error('description')
                <p class='text-danger'>{{$message}}</p>
            @enderror
        </div>

        <div class='form-group'>
            {!! Form::label('level', 'Level:') !!}
            {!! Form::number('level', null, ['class'=>'form-control']) !!}
            @error('level')
                <p class='text-danger'>{{$message}}</p>
            @enderror
        </div>

        <div class='form-group'>
            {!! Form::label('authority', 'Authority:') !!}
            {!! Form::text('authority', null, ['class'=>'form-control']) !!}
            @error('authority')
                <p class='text-danger'>{{$message}}</p>
            @enderror
        </div>

        <div class='form-group'>
            {!! Form::label('months_valid', 'Months Valid:') !!}
            {!! Form::number('months_valid', null, ['class'=>'form-control']) !!}
            @error('months_valid')
                <p class='text-danger'>{{$message}}</p>
            @enderror
        </div>

            {!! Form::submit('Save Changes', ['class'=>'btn btn-primary']) !!}

        {!! Form::close() !!}

    </div>

@stop

resources/views/certification_types/index.blade.php
@extends('layouts.app')

@section('content')

<h1>Certification Types</h1>

<div class="row justify-content-between">

    <!-- CREATE FORM -->
    <div class="col-6">

        {!! Form::open(['method'=>'POST', 'action'=>['CertificationTypeController@store'], 'files'=>false]) !!}

            <div class='form-group'>
                {!! Form::label('method', 'Method:') !!}
                {!! Form::text('method', null, ['class'=>'form-control']) !!}
                @error('method')
                    <p class='text-danger'>{{$message}}</p>
                @enderror
            </div>

            <div class='form-group'>
                {!! Form::label('code', 'Short Code:') !!}
                {!! Form::text('code', null, ['class'=>'form-control']) !!}
                @error('code')
                    <p class='text-danger'>{{$message}}</p>
                @enderror
            </div>

            <div class='form-group'>
                {!! Form::label('description', 'Description:') !!}
                {!! Form::textarea('description', null, ['class'=>'form-control ', 'rows'=>3]) !!}
                @error('description')
                    <p class='text-danger'>{{$message}}</p>
                @enderror
            </div>

            <div class='form-group'>
                {!! Form::label('level', 'Level:') !!}
                {!! Form::number('level', null, ['class'=>'form-control']) !!}
                @error('level')
                    <p class='text-danger'>{{$message}}</p>
                @enderror
            </div>

            <div class='form-group'>
                {!! Form::label('authority', 'Authority:') !!}
                {!! Form::text('authority', null, ['class'=>'form-control']) !!}
                @error('authority')
                    <p class='text-danger'>{{$message}}</p>
                @enderror
            </div>

            <div class='form-group'>
                {!! Form::label('months_valid', 'Months Valid:') !!}
                {!! Form::number('months_valid', null, ['class'=>'form-control']) !!}
                @error('months_valid')
                    <p class='text-danger'>{{$message}}</p>
                @enderror
            </div>

            {!! Form::submit('Create New', ['class'=>'btn btn-primary']) !!}

        {!! Form::close() !!}

    </div>

    <!-- INDEX TABLE -->
    <div class="col-5">

        <table class="table tabel-sm table-hover">

            <thead>
                <tr>
                    <th scope="col">Code</th>
                    <th scope="col">Method</th>
                </tr>
            </thead>

            <tbody>
                @if (count($certification_types) > 0)

                    @foreach ($certification_types as $certification_type)
                        <tr>
                            <th scope="row"><a href="{{route('certification_types.show', $certification_type)}}">{{$certification_type->code_level}}</a></th>
                            <td>{{$certification_type->method}}</td>
                        </tr>
                    @endforeach

                @else
                    <tr>
                        <th></th>
                        <td colspan="5">There are no certifications registered</td>
                    </tr>
                @endif
          </tbody>
        </table>


    </div>

</div>

@stop

resources/views/certification_types/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="row justify-content-between">

        <!-- DISPLAY CONTENT -->
        <div class="col-8">

            <h1>{{$certification_type->method}}</h1>

            <p>Authority: {{$certification_type->authority}}</p>
            <p>Code: {{$certification_type->code}}</p>
            <p>Level: {{$certification_type->level}}</p>

            <p>Expires: {{$certification_type->read_expiry}}</p>

            <p>Description:</p>
            <p>{{$certification_type->description}}</p>



        </div>

        <!-- ACTIONS -->
        @can('update', $certification_type)
        <div class="col-3 border border-info rounded">

            <br>

            <a href="{{route('certification_types.edit', $certification_type)}}" class="btn btn-secondary btn-block">Edit</a>

            <br>

            {!! Form::open(['method'=>'DELETE', 'action'=>['CertificationTypeController@destroy', $certification_type], 'files'=>false]) !!}

            {!! Form::submit('Delete Certification', ['class'=>'btn btn-danger btn-block']) !!}

            {!! Form::close() !!}

            <br>

        </div>
        @endcan


    </div>


@stop