routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register'=>false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware'=>['auth']], function()
{
    //users
    Route::resource('users', 'UserController');

    //certification types
    Route::resource('certification_types', 'CertificationTypeController');

    //certifications
    Route::group(['prefix'=>'certifications'], function(){
        Route::get('/expiring_index', 'CertificationController@expiringIndex')->name('certifications.expiring_index');
        Route::get('/download-document/{certification}', 'CertificationController@downloadDocument')->name('certifications.download_document');
    });
    Route::resource('certifications', 'CertificationController');

    //eye tests
    Route::group(['prefix'=>'eye_tests'], function(){
        Route::get('/expiring_index', 'EyeTestController@expiringIndex')->name('eye_tests.expiring_index');
        Route::get('/download-document/{eye_test}', 'EyeTestController@downloadDocument')->name('eye_tests.download_document');
    });
    Route::resource('eye_tests', 'EyeTestController');

    //equipment
    Route::resource('equipment', 'EquipmentController');

    // equipment calibrations
    Route::group(['prefix'=>'equipment_calibrations'], function(){
        Route::get('/download-document/{equipment_calibration}', 'EquipmentCalibrationController@downloadDocument')->name('equipment_calibrations.download_document');
        Route::get('/expiring_index', 'EquipmentCalibrationController@expiringIndex')->name('equipment_calibrations.expiring_index');
    });
    Route::resource('equipment_calibrations', 'EquipmentCalibrationController');

    // equipment users
    Route::group(['prefix'=>'equipment_users'], function(){
        Route::get('/return/{equipment_user}', 'EquipmentUserController@return')->name('equipment_users.return');
    });
    Route::resource('equipment_users', 'EquipmentUserController');
});

app/Certification.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\CertificationType;
use App\User;
use Carbon\Carbon;

class Certification extends Model
{

    // Status database constants
    const STATUS_ACTIVE = 1;
    const STATUS_EXPIRED = 2;

    // Properties
    protected $readStatuses = [
        self::STATUS_ACTIVE => 'Active',
        self::STATUS_EXPIRED => 'Expired',
    ];

    protected $fillable = [
        'certification_type_id', 'user_id', 'certified_by', 'document_path', 'certification_date', 'expiry_date', 'status', 'renewal_for_id', 'recertification_for_id',
    ];

    protected $reminder_period = 3; //months

    // Relationships
    public function certificationType()
    {
        return $this->belongsTo(CertificationType::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function renewal()
    {
        return $this->hasOne(self::class, 'renewal_for_id');
    }

    public function recertification()
    {
        return $this->hasOne(self::class, 'recertification_for_id');
    }

    // Accessors
    public function getTypeAttribute()
    {
        return $this->certificationType->method;
    }

    public function getReadStatusAttribute()
    {
        return $this->readStatuses[$this->status];
    }

    public function getCodeAttribute()
    {
        return $this->certificationType->code_level;
    }

    public function getDocumentStorePathAttribute()
    {
        return '/users/' . $this->user_id . '/certifications';
    }

    // Mutators



    // Scopes
    public function scopeGetRenewalRequired($query)
    {
        $date = Carbon::parse(date('Y-m-d'))->addMonths($this->reminder_period);
        return $query->where('renewal_for_id', null)
                        ->where('expiry_date', '<', $date)
                        ->whereDoesntHave('renewal')
                        ->get();
    }

    public function scopeGetRecertificationRequired($query)
    {
        $date = Carbon::parse(date('Y-m-d'))->addMonths($this->reminder_period);
        return $query->where('renewal_for_id', '!=', null)
                        ->where('expiry_date', '<', $date)
                        ->whereDoesntHave('recertification')
                        ->get();
    }

    public function scopeGetExpires($query)
    {
        $date = Carbon::parse(date('Y-m-d'));
        return $query->where('expiry_date', '<', $date)
                        ->get();
    }

    // Context
    public function requiresRenewal()
    {
        if ($this->renewal_for_id == null)
        {
            return true;
        }
    }

    public function requiresRecertification()
    {
        if ($this->renewal_for_id != null)
        {
            return true;
        }
    }
}

app/CertificationType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CertificationType extends Model
{

    protected $fillable = [
        'method', 'code', 'description', 'level', 'authority', 'months_valid',
    ];

    protected $appends = [
        'code_level'
    ];

    // Accessors
    public function getReadExpiryAttribute()
    {
        return "This certification needs to be renewed every " . $this->months_valid . " months";
    }

    public function getCodeLevelAttribute()
    {
        return $this->code.'-'.$this->level;
    }
}

app/Http/Controllers/CertificationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Certification;
use App\CertificationType;
use App\User;
use App\Http\Requests\CertificationRequest;
use App\StatusHandlers\CertificationStatusHandler\CertificationState;
use App\ModelLogic\Certification\CertificationLogic;
use App\ExternalServices\FileStorage\DocumentHandler;


class CertificationController extends Controller
{
    public function __construct(CertificationState $statusLogic, CertificationLogic $certificationLogic)
    {
        $this->statusHandler = $statusLogic;
        $this->certificationLogic = $certificationLogic;
        $this->middleware('admin');
        $this->authorizeResource(Certification::class);
    }

    /**
    * Return an index of all certifications that require renewal or re-certification
    *
    * @return Illuminate\Http\Response
    */
    public function expiringIndex()
    {
        $certifications_renewal = Certification::getRenewalRequired();
        $certifications_recertification = Certification::getRecertificationRequired();

        return view('certifications.expiring_index', compact('certifications_renewal', 'certifications_recertification'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param \Illuminate\Http\Requests $request
     *
     * @return \Illuminate\Http\Response
     * passes to form
     * user_id -> user to receive certification
     * certification_id -> used in context of recertification and renewals
     * certification_types -> optional CertificationType
     */
    public function create(Request $request)
    {
        $user = User::findOrFail($request->user_id);
        $certification = Certification::find($request->certification_id); // for recertifications or renewals
        $certification_types = CertificationType::all()->pluck('code_level', 'id')->toArray();

        return view('certifications.create', compact('user', 'certification', 'certification_types'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CertificationRequest $request)
    {
        $this->certificationLogic->create($request);

        return redirect(route('users.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Certification $certification)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Certification $certification)
    {
        return view('certifications.edit', compact('certification'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CertificationRequest $request, Certification $certification)
    {
        $this->certificationLogic->update($request, $certification);

        return redirect(route('users.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Certification $certification)
    {
        $this->certificationLogic->delete($certification);

        return redirect(route('users.index'));
    }

    public function downloadDocument(Certification $certification)
    {
        return DocumentHandler::download($certification->document_path);
    }

}

resources/views/certifications/create.blade.php
@extends('layouts.app')

@section('content')

    <h1>Add certification for {{$user->name}}</h1>

    <br>

    {!! Form::open(['method'=>'POST', 'action'=>['CertificationController@store'], 'files'=>true]) !!}

    {!! Form::hidden('user_id', $user->id) !!}

        @if ($certification)

            {!! Form::hidden('certification_id', $certification->id) !!}

            <div class='form-group'>
                {!! Form::label('certification_type_id', 'Certification Type:') !!}
                {!! Form::select('certification_type_id', [$certification->certificationType->id =>$certification_types[$certification->certificationType->id]], null, ['class'=>'form-control', 'readonly'=>true]) !!}
                @error('certification_type_id')
                    <p class='text-danger'>{{$message}}</p>
                @enderror
            </div>
        @else
            <div class='form-group'>
                {!! Form::label('certification_type_id', 'Certification Type:') !!}
                {!! Form::select('certification_type_id', [''=>'Select Certification'] + $certification_types, null, ['class'=>'form-control']) !!}
                @error('certification_type_id')
                    <p class='text-danger'>{{$message}}</p>
                @enderror
            </div>
        @endif

        <div class='form-group'>
            {!! Form::label('certified_by', 'Certified By:') !!}
            {!! Form::text('certified_by', null, ['class'=>'form-control']) !!}
            @error('certified_by')
                <p class='text-danger'>{{$message}}</p>
            @enderror
        </div>

        <div class='form-group'>
            {!! Form::label('file', 'Add File:') !!}<br>
            {!! Form::file('file') !!}
            @error('file')
                <p class='text-danger'>{{$message}}</p>
            @enderror
        </div>

        <div class='form-group'>
            {!! Form::label('certification_date', 'Certification Date:') !!}
            {!! Form::date('certification_date', null, ['class'=>'form-control']) !!}
            @error('certification_date')
                <p class='text-danger'>{{$message}}</p>
            @enderror
        </div>

        {!! Form::submit('Add Certificate', ['class'=>'btn btn-primary']) !!}

    {!! Form::close() !!}

@stop

resources/views/certifications/edit.blade.php
@extends('layouts.app')

@section('content')

    <h1>Update certification for {{$certification->user->name}}</h1>

    {!! Form::model($certification, ['method'=>'PATCH', 'action'=>['CertificationController@update', $certification], 'files'=>true]) !!}

        <div class='form-group'>
            {!! Form::label('certification_type_id', 'Certification Type:') !!}
            {!! Form::select('certification_type_id', [$certification->certificationType->id => $certification->code], null, ['class'=>'form-control', 'readonly'=>'true']) !!}
            @error('certification_type_id')
                <p class='text-danger'>{{$message}}</p>
            @enderror
        </div>

        <div class='form-group'>
            {!! Form::label('certified_by', 'Certified By:') !!}
            {!! Form::text('certified_by', null, ['class'=>'form-control']) !!}
            @error('certified_by')
                <p class='text-danger'>{{$message}}</p>
            @enderror
        </div>

        <div class='form-group'>
            {!! Form::label('file', 'Add File:') !!}<br>
            {!! Form::file('file') !!}
            @error('file')
                <p class='text-danger'>{{$message}}</p>
            @enderror
        </div>

        <div class='form-group'>
            {!! Form::label('certification_date', 'Certification Date:') !!}
            {!! Form::date('certification_date', null, ['class'=>'form-control']) !!}
            @error('certification_date')
                <p class='text-danger'>{{$message}}</p>
            @enderror
        </div>

        {!! Form::submit('Save Changes', ['class'=>'btn btn-secondary']) !!}

    {!! Form::close() !!}

@stop

resources/views/certifications/expiring_index.blade.php
@extends('layouts.app')

@section('content')

    <h1>Expiring Certifications</h1>

    <!-- EXPIRING CERTFICATIONS NAV -->
    <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <a class="nav-item nav-link active" id="nav-renewal-tab" data-toggle="tab" href="#nav-renewal" role="tab" aria-controls="nav-renewal" aria-selected="false">Renewals</a>
            <a class="nav-item nav-link" id="nav-recertifications-tab" data-toggle="tab" href="#nav-recertifications" role="tab" aria-controls="nav-recertifications" aria-selected="false">Re-Certifications</a>
        </div>
    </nav>
    <div class="tab-content" id="nav-tabContent">
        <!-- RENEWALS -->
        <div class="tab-pane fade show active" id="nav-renewal" role="tabpanel" aria-labelledby="nav-renewal-tab">

            <br>

            <table class="table tabel-sm table-hover">

                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Code</th>
                        <th scope="col">User</th>
                        <th scope="col">Status</th>
                        <th scope="col">Certification Date</th>
                        <th scope="col">Expiry Date</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>

                <tbody>
                    @if (count($certifications_renewal) > 0)

                        @foreach ($certifications_renewal as $certification)
                            <tr>
                                <th scope="row">{{$certification->id}}</th>
                                <td><a href="{{route('certification_types.show', $certification->certificationType)}}">{{$certification->code}}</a></td>
                                <td>{{$certification->user->name}}</td>
                                <td>{{$certification->read_status}}</td>
                                <td>{{$certification->certification_date}}</td>
                                <td>{{$certification->expiry_date}}</td>
                                <td>
                                    {!! Form::open(['method'=>'GET', 'action'=>['CertificationController@create'], 'files'=>false]) !!}

                                        {!! Form::hidden('user_id', $certification->user->id) !!}

                                        {!! Form::hidden('certification_id', $certification->id) !!}

                                        {!! Form::submit('Renew', ['class'=>'btn btn-sm btn-success']) !!}

                                    {!! Form::close() !!}
                                </td>
                            </tr>
                        @endforeach

                    @else
                        <tr>
                            <th></th>
                            <td colspan="5">There are no certifications requiring renewal</td>
                        </tr>
                    @endif
              </tbody>
            </table>

        </div>
        
        <!-- RE-CERTIFICATIONS -->
        <div class="tab-pane fade" id="nav-recertifications" role="tabpanel" aria-labelledby="nav-recertifications-tab">

            <br>

            <table class="table tabel-sm table-hover">

                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Code</th>
                        <th scope="col">User</th>
                        <th scope="col">Status</th>
                        <th scope="col">Certification Date</th>
                        <th scope="col">Expiry Date</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>

                <tbody>
                    @if (count($certifications_recertification) > 0)

                        @foreach ($certifications_recertification as $certification)
                            <tr>
                                <th scope="row">{{$certification->id}}</th>
                                <td><a href="{{route('certification_types.show', $certification->certificationType)}}">{{$certification->code}}</a></td>
                                <td>{{$certification->user->name}}</td>
                                <td>{{$certification->read_status}}</td>
                                <td>{{$certification->certification_date}}</td>
                                <td>{{$certification->expiry_date}}</td>
                                <td>
                                    {!! Form::open(['method'=>'GET', 'action'=>['CertificationController@create'], 'files'=>false]) !!}

                                        {!! Form::hidden('user_id', $certification->user->id) !!}

                                        {!! Form::hidden('certification_id', $certification->id) !!}

                                        {!! Form::submit('Re-Certify', ['class'=>'btn btn-sm btn-success']) !!}

                                    {!! Form::close() !!}
                                </td>
                            </tr>
                        @endforeach

                    @else
                        <tr>
                            <th></th>
                            <td colspan="5">There are no certifications requiring re-certification</td>
                        </tr>
                    @endif
              </tbody>
            </table>

        </div>
    </div>


@endsection